# Generated by Django 6.0.2 on 2026-02-05 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_threshold', models.FloatField(default=3.0, help_text='Distancia para considerar llegada al nodo (m)')),
                ('arrival_threshold_maneuver', models.FloatField(default=0.5, help_text='Distancia para llegada en maniobras (m)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
