# Generated by Django 6.0.2 on 2026-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='lookahead_distance',
            field=models.FloatField(default=2.0, help_text='Distancia de visión a futuro (m)'),
        ),
    ]
