# Generated by Django 6.0.2 on 2026-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simconfig_lookahead_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='backward_weight',
            field=models.FloatField(default=30.0, help_text='Penalización por ir marcha atrás'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='base_speed',
            field=models.FloatField(default=0.4, help_text='Velocidad base en rectas'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='gear_switch_cost',
            field=models.FloatField(default=150.0, help_text='Penalización por cambio de marcha'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='steering_cost',
            field=models.FloatField(default=20.0, help_text='Penalización por girar'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='steering_kp',
            field=models.FloatField(default=5.0, help_text='Ganancia proporcional del volante (Sensibilidad)'),
        ),
    ]
