# Generated by Django 6.0.2 on 2026-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_simconfig_backward_weight_simconfig_base_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='arrival_threshold_curve',
            field=models.FloatField(default=1.5, help_text='Distancia para llegada en curvas (m)'),
        ),
    ]
