# Generated by Django 6.0.2 on 2026-02-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_simconfig_arrival_threshold_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='base_heuristic_weight',
            field=models.FloatField(default=50.0, help_text='Peso de la heurística (Distancia Euclídea)'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='debug_iter_limit',
            field=models.IntegerField(default=50000, help_text='Límite máximo de iteraciones A*'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='gradient_weight',
            field=models.FloatField(default=5.0, help_text='Peso del campo de gradiente (Costo Mapa)'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='vehicle_length',
            field=models.FloatField(default=3.0, help_text='Largo del vehículo (m)'),
        ),
        migrations.AddField(
            model_name='simconfig',
            name='vehicle_width',
            field=models.FloatField(default=1.5, help_text='Ancho del vehículo (m)'),
        ),
    ]
