# Generated by Django 4.2.11 on 2026-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_simconfig_base_heuristic_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='step_size',
            field=models.FloatField(default=1.5, help_text='Resolución de paso A* (m)'),
        ),
        migrations.AlterField(
            model_name='simconfig',
            name='debug_iter_limit',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='simconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
