# Generated by Django 4.2.11 on 2026-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_simconfig_step_size_alter_simconfig_debug_iter_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconfig',
            name='steering_change_cost',
            field=models.FloatField(default=5.0, help_text='Penalización por cambiar el giro (Suavidad)'),
        ),
    ]
