# Generated by Django 4.2.11 on 2026-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_simconfig_steering_change_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simconfig',
            name='steering_change_cost',
            field=models.FloatField(default=0.1, help_text='Penalización por cambiar el giro (Suavidad)'),
        ),
        migrations.AlterField(
            model_name='simconfig',
            name='steering_cost',
            field=models.FloatField(default=0.5, help_text='Penalización por girar'),
        ),
    ]
