# Generated by Django 6.0.2 on 2026-02-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_simconfig_steering_change_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simconfig',
            old_name='arrival_threshold_maneuver',
            new_name='arrival_threshold_gear',
        ),
        migrations.AddField(
            model_name='simconfig',
            name='collision_margin',
            field=models.FloatField(default=0.7, help_text='Margen de seguridad para colisiones (m)'),
        ),
        migrations.AlterField(
            model_name='simconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
